In [1]:
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

Using TensorFlow backend.


In [2]:
model = Sequential()

In [3]:
model.add(Convolution2D(32,3,3,input_shape=(64,64,3),activation='relu'))

/home/aswin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(64, 64, 3..., activation="relu")`
  """Entry point for launching an IPython kernel.


In [4]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [5]:
model.add(Flatten())

In [6]:
model.add(Dense(output_dim = 128, activation = 'relu'))
model.add(Dense(output_dim = 1, activation = 'sigmoid'))

/home/aswin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128)`
  """Entry point for launching an IPython kernel.
/home/aswin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  


In [7]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [8]:
from keras.preprocessing.image import ImageDataGenerator


In [9]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

In [10]:
test_datagen = ImageDataGenerator(rescale = 1./255)


In [11]:
training_set = train_datagen.flow_from_directory('dataset/training_set',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')

Found 8000 images belonging to 2 classes.


In [12]:
test_set = test_datagen.flow_from_directory('dataset/test_set',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'binary')

Found 2000 images belonging to 2 classes.


In [14]:
model.fit_generator(training_set,
                         samples_per_epoch = 8000,
                         nb_epoch = 25,
                         validation_data = test_set,
                         nb_val_samples = 2000)

/home/aswin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: The semantics of the Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Basically steps_per_epoch = samples_per_epoch/batch_size. Similarly `nb_val_samples`->`validation_steps` and `val_samples`->`steps` arguments have changed. Update your method calls accordingly.
  """
/home/aswin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<keras.pre..., validation_data=<keras.pre..., steps_per_epoch=250, epochs=25, validation_steps=2000)`
  """


Epoch 1/25
250/250 [==============================] - 205s 821ms/step - loss: 0.6053 - accuracy: 0.6795 - val_loss: 0.6990 - val_accuracy: 0.6706
Epoch 2/25
250/250 [==============================] - 206s 823ms/step - loss: 0.5751 - accuracy: 0.7028 - val_loss: 0.5559 - val_accuracy: 0.7087
Epoch 3/25
250/250 [==============================] - 204s 817ms/step - loss: 0.5640 - accuracy: 0.7117 - val_loss: 0.4541 - val_accuracy: 0.7124
Epoch 4/25
250/250 [==============================] - 204s 816ms/step - loss: 0.5397 - accuracy: 0.7258 - val_loss: 0.5213 - val_accuracy: 0.7248
Epoch 5/25
250/250 [==============================] - 204s 817ms/step - loss: 0.5302 - accuracy: 0.7343 - val_loss: 0.6420 - val_accuracy: 0.6832
Epoch 6/25
250/250 [==============================] - 204s 817ms/step - loss: 0.5195 - accuracy: 0.7416 - val_loss: 0.5689 - val_accuracy: 0.7457
Epoch 7/25
250/250 [==============================] - 204s 815ms/step - loss: 0.5113 - accuracy: 0.7459 - val_loss: 0.4303 -

In [48]:
import numpy as np
from keras.preprocessing import image

In [61]:
test_image = image.load_img('dataset/te',target_size=(64,64))

In [80]:
# test_image = image.img_to_array(test_set)
# test_image = np.expand_dims(test_image,axis=0)

result = model.predict(test_set)

In [81]:
result

array([[0.06881711],
       [0.87416065],
       [0.5819689 ],
       ...,
       [0.86871374],
       [0.06381351],
       [0.9787291 ]], dtype=float32)

In [82]:
if result[0][0]>0.5:
    print('dog')
else:
    print('cat')

cat


In [83]:
test_set.labels

array([0, 0, 0, ..., 1, 1, 1], dtype=int32)

In [84]:
from sklearn.metrics import confusion_matrix

In [86]:
print(confusion_matrix(np.round(result),test_set.labels))

[[511 517]
 [489 483]]


In [87]:
from sklearn.metrics import accuracy_score

In [89]:
accuracy_score(test_set.labels,np.round(result))

0.497